development:
  adapter: redis
  url: <%= ENV.fetch('ACTION_CABLE_REDIS_URL', 'redis://127.0.0.1:6379/1') %>

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV.fetch('ACTION_CABLE_REDIS_URL', 'redis://127.0.0.1:6379/1') %>

production:
  adapter: redis
  url: <%= ENV.fetch('ACTION_CABLE_REDIS_URL', 'redis://127.0.0.1:6379/1') %>